# Generated by Django 5.2.1 on 2025-06-06 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('attended', '已出席'), ('absent', '缺席'), ('late', '遲到'), ('excused', '已請假')], default='attended', max_length=10, verbose_name='出席狀況')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to=settings.AUTH_USER_MODEL, verbose_name='家長')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_records', to='service.service', verbose_name='服務')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_records', to='service.timeslot', verbose_name='時段')),
            ],
            options={
                'verbose_name': '家長活動紀錄',
                'verbose_name_plural': '家長活動紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('attended', '已出席'), ('absent', '缺席'), ('late', '遲到'), ('excused', '已請假')], default='attended', max_length=10, verbose_name='出席狀況')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='service.service', verbose_name='服務')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='student.student', verbose_name='學生')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='service.timeslot', verbose_name='時段')),
            ],
            options={
                'verbose_name': '學生活動紀錄',
                'verbose_name_plural': '學生活動紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_attachments/', verbose_name='附件(圖片或影片)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('parent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activity_record.parentrecord', verbose_name='家長活動紀錄附件')),
                ('student_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activity_record.studentrecord', verbose_name='學生活動紀錄附件')),
            ],
            options={
                'verbose_name': '活動附件',
                'verbose_name_plural': '活動附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
