# Generated by Django 5.2.1 on 2025-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='導師姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
            ],
            options={
                'verbose_name': '導師',
                'verbose_name_plural': '導師',
            },
        ),
    ]
