version: "3.9"

services:
  web:
    env_file:
      - .env-staging
    ports:
      - "8081:8000"      # Map container port 8000 to host 8081 for staging
    restart: unless-stopped

  nginx:
    ports:
      - "8082:80"        # Staging nginx on host port 8082 to avoid conflict with prod
      - "8443:443"

  db:
    env_file:
      - .env-staging
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
      
  redis:
    volumes:
      - redisdata_staging:/data

volumes:
  pgdata_staging:
  redisdata_staging:
