# Generated by Django 5.2.1 on 2025-06-13 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='優惠碼')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金額')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='折扣百分比')),
                ('valid_from', models.DateTimeField(verbose_name='有效開始日期')),
                ('valid_to', models.DateTimeField(verbose_name='有效結束日期')),
                ('active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('quota', models.PositiveIntegerField(blank=True, null=True, verbose_name='總使用次數限制')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次數')),
                ('user_quota', models.PositiveIntegerField(blank=True, null=True, verbose_name='每用戶使用次數限制')),
                ('users', models.ManyToManyField(blank=True, help_text='允許使用此優惠券的用戶，留空表示所有用戶均可使用', related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='指定用戶')),
            ],
        ),
    ]
