# Generated by Django 5.2.1 on 2025-06-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the coupon', null=True, verbose_name='簡介'),
        ),
    ]
