# Generated by Django 5.2.1 on 2025-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('product_type', models.CharField(choices=[('physical', '實體商品'), ('virtual', '虛擬商品')], default='physical', max_length=20, verbose_name='商品類型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='庫存數量')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='庫存單位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
            },
        ),
    ]
