# Generated by Django 5.2.1 on 2025-06-13 08:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active'),
        ('payment', '0002_payment_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='方案編號')),
                ('name', models.CharField(max_length=100, verbose_name='方案名稱')),
                ('description', models.TextField(verbose_name='方案描述')),
                ('billing_cycle', models.CharField(choices=[('monthly', '月費'), ('annual', '年費'), ('lifetime', '終身')], default='monthly', max_length=20, verbose_name='計費週期')),
                ('duration_days', models.PositiveIntegerField(verbose_name='有效天數')),
                ('features', models.JSONField(default=dict, verbose_name='方案功能')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '訂閱方案',
                'verbose_name_plural': '訂閱方案',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日期')),
                ('end_date', models.DateTimeField(verbose_name='結束日期')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已過期'), ('canceled', '已取消'), ('past_due', '逾期未付')], default='active', max_length=20, verbose_name='狀態')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='自動續訂')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='試用開始')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='試用結束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment', verbose_name='關聯付款')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscriptionplan', verbose_name='訂閱方案')),
            ],
            options={
                'verbose_name': '訂閱紀錄',
                'verbose_name_plural': '訂閱紀錄',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('member_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membertier', verbose_name='會員等級')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='subscription.subscriptionplan', verbose_name='訂閱方案')),
            ],
            options={
                'verbose_name': '訂閱方案價格',
                'verbose_name_plural': '訂閱方案價格',
                'unique_together': {('plan', 'member_tier')},
            },
        ),
    ]
