# Generated by Django 5.2.1 on 2025-06-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('currency', models.CharField(default='HKD', max_length=10, verbose_name='貨幣')),
                ('status', models.CharField(choices=[('pending', '處理中'), ('completed', '已完成'), ('failed', 'Failed'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='付款狀態')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='交易編號')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='付款方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking', verbose_name='預約')),
            ],
            options={
                'verbose_name': '付款',
                'verbose_name_plural': '付款紀錄',
            },
        ),
    ]
