# Generated by Django 5.2.1 on 2025-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=255, verbose_name='中文名稱')),
                ('name_eng', models.CharField(max_length=255, verbose_name='English Name')),
                ('address', models.TextField(verbose_name='地址')),
                ('district', models.CharField(choices=[('中西區', '中西區'), ('東區', '東區'), ('灣仔區', '灣仔區'), ('南區', '南區'), ('九龍城區', '九龍城區'), ('觀塘區', '觀塘區'), ('深水埗區', '深水埗區'), ('黃大仙區', '黃大仙區'), ('油尖旺區', '油尖旺區'), ('元朗區', '元朗區'), ('屯門區', '屯門區'), ('西貢區', '西貢區'), ('北區', '北區'), ('沙田區', '沙田區'), ('大埔區', '大埔區'), ('葵青區', '葵青區'), ('荃灣區', '荃灣區'), ('離島區', '離島區')], max_length=20, verbose_name='區域')),
                ('area', models.CharField(choices=[('香港島', '香港島'), ('九龍', '九龍'), ('新界', '新界'), ('離島', '離島')], max_length=10, verbose_name='地區')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], max_length=10, verbose_name='類別')),
            ],
        ),
    ]
