# Generated by Django 5.2.1 on 2025-06-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '學校', 'verbose_name_plural': '學校列表'},
        ),
    ]
