# Generated by Django 5.2.1 on 2025-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('social_development', '群育'), ('hospital_school', '醫院學校'), ('physical_disability', '肢體傷殘'), ('visual_impairment', '視障'), ('hearing_impairment', '聽障'), ('mild_intellectual_disability', '輕度智障'), ('moderate_intellectual_disability', '中度智障'), ('mild_to_moderate_intellectual_disability', '輕中度智障'), ('severe_intellectual_disability', '嚴重智障'), ('mixed_intellectual_disability', '混合程度智障')], max_length=50, verbose_name='類別'),
        ),
    ]
