# Generated by Django 5.2.1 on 2025-06-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.CharField(choices=[('香港島', '香港島'), ('九龍', '九龍'), ('新界', '新界'), ('離島', '離島')], max_length=50, verbose_name='地區'),
        ),
    ]
