# Generated by Django 5.2.1 on 2025-06-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='程度')),
            ],
            options={
                'verbose_name': '程度',
                'verbose_name_plural': '程度',
            },
        ),
        migrations.CreateModel(
            name='SenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='狀態')),
            ],
            options={
                'verbose_name': '狀態',
                'verbose_name_plural': '狀態',
            },
        ),
        migrations.CreateModel(
            name='SenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='特殊教育需求類型')),
            ],
            options={
                'verbose_name': '特殊教育需求類型',
                'verbose_name_plural': '特殊教育需求類型',
            },
        ),
        migrations.CreateModel(
            name='Sen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='學生編號')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sen.senlevel', verbose_name='程度')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sen.senstatus', verbose_name='狀態')),
                ('sen_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sen.sentype', verbose_name='特殊教育需求類型')),
            ],
            options={
                'verbose_name': '特殊教育需求',
                'verbose_name_plural': '特殊教育需求',
            },
        ),
    ]
