# Generated by Django 5.2.1 on 2025-06-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sen', '0001_initial'),
        ('student', '0005_alter_student_id_alter_student_id_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sen',
            name='student_id',
        ),
        migrations.AddField(
            model_name='sen',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sens', to='student.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='senlevel',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='senstatus',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sentype',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
