# Generated by Django 5.2.1 on 2025-05-30 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membertier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.membertier'),
        ),
    ]
