# Generated by Django 5.2.1 on 2025-06-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='狀態')),
            ],
            options={
                'verbose_name': '預約狀態',
                'verbose_name_plural': '預約狀態',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='服務')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.timeslot', verbose_name='時段')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.bookingstatus', verbose_name='預約狀態')),
            ],
            options={
                'verbose_name': '預約',
                'verbose_name_plural': '預約',
            },
        ),
    ]
