# Generated by Django 5.2.1 on 2025-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('student', '0008_alter_student_grade_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.student', verbose_name='學生'),
        ),
    ]
