# Generated by Django 5.2.1 on 2025-06-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(
                    primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('price_desc', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(verbose_name='人數')),
                ('need_timeslot', models.BooleanField(default=False)),
                ('promote_label', models.CharField(blank=True, max_length=255)),
                ('mentor', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='service.mentor')),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='service.organization')),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='service.servicestatus')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(verbose_name='人數')),
                ('status', models.CharField(choices=[('available', 'Available'), (
                    'unavailable', 'Unavailable'), ('full', 'Full')], default='available', max_length=20)),
                ('current_headcount', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='time_slots', to='service.service')),
            ],
            options={
                'ordering': ['start_datetime'],
                'unique_together': {('service', 'start_datetime')},
            },
        ),
    ]
