# Generated by Django 5.2.1 on 2025-06-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='導師姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='機構名稱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('website', models.URLField(blank=True, verbose_name='網站')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='聯絡人')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='狀態')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Display Name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='服務名稱')),
                ('detail', models.TextField(blank=True, verbose_name='詳細內容')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('price_desc', models.TextField(blank=True, verbose_name='價格說明')),
                ('location', models.CharField(max_length=255, verbose_name='地點')),
                ('capacity', models.PositiveIntegerField(verbose_name='人數')),
                ('promote_label', models.CharField(blank=True, max_length=255, verbose_name='推廣標籤')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='活動開始日期')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='活動結束日期')),
                ('min_selection', models.PositiveIntegerField(default=1, verbose_name='最少選擇')),
                ('max_selection', models.PositiveIntegerField(default=1, verbose_name='最多選擇')),
                ('mentors', models.ManyToManyField(blank=True, to='service.mentor', verbose_name='導師')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.organization', verbose_name='機構')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.servicestatus', verbose_name='狀態')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='開始時間')),
                ('capacity', models.PositiveIntegerField(verbose_name='人數')),
                ('status', models.CharField(choices=[('available', '可預約'), ('unavailable', '不可預約'), ('full', '已額滿'), ('in-progress', '進行中'), ('finished', '已完結'), ('cancelled', '已取消'), ('postponed', '延期')], default='available', max_length=20, verbose_name='狀態')),
                ('current_headcount', models.PositiveIntegerField(default=0, verbose_name='現時人數')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='service.service', verbose_name='服務')),
            ],
            options={
                'verbose_name': '時段',
                'verbose_name_plural': '時段',
                'ordering': ['start_datetime'],
                'unique_together': {('service', 'start_datetime')},
            },
        ),
    ]
