# Generated by Django 5.2.1 on 2025-06-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_child_fee',
            field=models.IntegerField(default=0, verbose_name='超過的子女每位收費'),
        ),
        migrations.AddField(
            model_name='service',
            name='free_accompanying_children',
            field=models.PositiveIntegerField(default=1, verbose_name='免費可同行的子女數'),
        ),
    ]
