# Generated by Django 5.2.1 on 2025-06-09 02:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_extra_child_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail',
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name='詳細內容'),
        ),
    ]
