# Generated by Django 5.2.1 on 2025-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='訂金(%)'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_selection',
            field=models.PositiveIntegerField(default=1, verbose_name='最多選擇時段'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_selection',
            field=models.PositiveIntegerField(default=1, verbose_name='最少選擇時段'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
    ]
