# Generated by Django 5.2.1 on 2025-06-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicetype_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
    ]
