# Generated by Django 5.2.1 on 2025-06-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_datetime'], 'verbose_name': '時段', 'verbose_name_plural': '時段'},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('service', 'start_datetime')},
        ),
    ]
