# Generated by Django 5.2.1 on 2025-06-09 05:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='詳細內容'),
        ),
    ]
