# Generated by Django 5.2.1 on 2025-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_service_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='capacity',
            field=models.TextField(blank=True, verbose_name='人數 (e.g. 12人)'),
        ),
    ]
