# Generated by Django 5.2.1 on 2025-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': '導師', 'verbose_name_plural': '導師'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '機構', 'verbose_name_plural': '機構'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '服務', 'verbose_name_plural': '服務'},
        ),
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'verbose_name': '服務狀態', 'verbose_name_plural': '服務狀態'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': '服務類型', 'verbose_name_plural': '服務類型'},
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='顯示名稱'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='服務類型名稱'),
        ),
    ]
