# Generated by Django 5.2.1 on 2025-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        ('service', '0011_alter_mentor_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.AlterField(
            model_name='service',
            name='mentors',
            field=models.ManyToManyField(blank=True, to='mentor.mentor', verbose_name='導師'),
        ),
    ]
