# Generated by Django 5.2.1 on 2025-06-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_delete_mentor_alter_service_mentors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
