# Generated by Django 5.2.1 on 2025-06-09 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.school', verbose_name='學校'),
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '年級', 'verbose_name_plural': '年級'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '學生', 'verbose_name_plural': '學生'},
        ),
        migrations.AlterModelOptions(
            name='studentsession',
            options={'verbose_name': '學生會話', 'verbose_name_plural': '學生會話'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=100, verbose_name='年級'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='家長'),
        ),
        migrations.AlterField(
            model_name='student',
            name='strn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='STRN'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='會話編號'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
