# Generated by Django 5.2.1 on 2025-06-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_school_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsession',
            options={'verbose_name': 'Student Session', 'verbose_name_plural': 'Student Session'},
        ),
    ]
