# Generated by Django 5.2.1 on 2025-06-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options'),
        ('student', '0003_alter_studentsession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='student.grade', verbose_name='就讀年級'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HKID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.school', verbose_name='學校'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='SessionId'),
        ),
    ]
