# Generated by Django 5.2.1 on 2025-06-13 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_date_of_birth_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='HKID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='strn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='STRN'),
        ),
    ]
