# Generated by Django 5.2.1 on 2025-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_id_alter_student_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='id_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='HKID'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='strn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='STRN'),
        ),
    ]
