# Generated by Django 5.2.1 on 2025-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentsession_id_no_studentsession_strn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
