# Generated by Django 5.2.1 on 2025-06-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_alter_student_id_alter_student_id_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HollandCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_code', models.CharField(max_length=10, verbose_name='First Code')),
                ('second_code', models.CharField(max_length=10, verbose_name='Second Code')),
                ('third_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Third Code')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': 'HollandCode',
                'verbose_name_plural': 'HollandCode',
            },
        ),
    ]
