# Generated by Django 5.2.1 on 2025-06-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holland_code', '0001_initial'),
        ('student', '0005_alter_student_id_alter_student_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollandcode',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holland_codes', to='student.student', verbose_name='Student'),
        ),
    ]
