# Generated by Django 5.2.1 on 2025-06-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holland_code', '0002_alter_hollandcode_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollandcode',
            name='first_code',
            field=models.CharField(choices=[('R', 'R'), ('I', 'I'), ('A', 'A'), ('S', 'S'), ('E', 'E'), ('C', 'C')], max_length=10, verbose_name='First Code'),
        ),
        migrations.AlterField(
            model_name='hollandcode',
            name='second_code',
            field=models.CharField(choices=[('R', 'R'), ('I', 'I'), ('A', 'A'), ('S', 'S'), ('E', 'E'), ('C', 'C')], max_length=10, verbose_name='Second Code'),
        ),
        migrations.AlterField(
            model_name='hollandcode',
            name='third_code',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('I', 'I'), ('A', 'A'), ('S', 'S'), ('E', 'E'), ('C', 'C')], max_length=10, null=True, verbose_name='Third Code'),
        ),
    ]
